更新

diff --git a/build/azure-pipelines/web/product-build-web.yml b/build/azure-pipelines/web/product-build-web.yml
--- a/build/azure-pipelines/web/product-build-web.yml
+++ b/build/azure-pipelines/web/product-build-web.yml
@@ -1,113 +1,192 @@
-steps:
-- script: |
-    mkdir -p .build
-    echo -n $BUILD_SOURCEVERSION > .build/commit
-    echo -n $VSCODE_QUALITY > .build/quality
-  displayName: Prepare cache flag
+jobs:
+  - job: Web
+    displayName: Web
+    timeoutInMinutes: 45
+    pool:
+      name: 1es-ubuntu-22.04-x64
+      os: linux
+    variables:
+      VSCODE_ARCH: x64
+      BUILDS_API_URL: $(System.CollectionUri)$(System.TeamProject)/_apis/build/builds/$(Build.BuildId)/
+    templateContext:
+      outputs:
+        - output: pipelineArtifact
+          targetPath: $(Build.ArtifactStagingDirectory)/out/web/vscode-web.tar.gz
+          artifactName: vscode_web_linux_standalone_archive-unsigned
+          displayName: Publish web archive
+          sbomBuildDropPath: $(Agent.BuildDirectory)/vscode-web
+          sbomPackageName: "VS Code Linux x64 Web (Standalone)"
+          sbomPackageVersion: $(Build.SourceVersion)
+    steps:
+      - template: ../common/checkout.yml@self
 
-- task: 1ESLighthouseEng.PipelineArtifactCaching.RestoreCacheV1.RestoreCache@1
-  inputs:
-    keyfile: 'build/.cachesalt, .build/commit, .build/quality'
-    targetfolder: '.build, out-build, out-vscode-min, out-vscode-reh-min, out-vscode-reh-web-min'
-    vstsFeed: 'npm-vscode'
-    platformIndependent: true
-    alias: 'Compilation'
+      - task: NodeTool@0
+        inputs:
+          versionSource: fromFile
+          versionFilePath: .nvmrc
 
-- script: |
-    set -e
-    exit 1
-  displayName: Check RestoreCache
-  condition: and(succeeded(), ne(variables['CacheRestored-Compilation'], 'true'))
+      - template: ../distro/download-distro.yml@self
 
-- task: NodeTool@0
-  inputs:
-    versionSpec: "12.14.1"
+      - task: AzureKeyVault@2
+        displayName: "Azure Key Vault: Get Secrets"
+        inputs:
+          azureSubscription: vscode-oss-build-secrets
+          KeyVaultName: vscode-oss-build-secrets
+          SecretsFilter: "github-token-code-oss"
 
-- task: geeklearningio.gl-vsts-tasks-yarn.yarn-installer-task.YarnInstaller@2
-  inputs:
-    versionSpec: "1.x"
+      - script: node build/setup-npm-registry.ts $NPM_REGISTRY
+        condition: and(succeeded(), ne(variables['NPM_REGISTRY'], 'none'))
+        displayName: Setup NPM Registry
 
-- task: AzureKeyVault@1
-  displayName: 'Azure Key Vault: Get Secrets'
-  inputs:
-    azureSubscription: 'vscode-builds-subscription'
-    KeyVaultName: vscode
+      - script: mkdir -p .build && node build/azure-pipelines/common/computeNodeModulesCacheKey.ts web $(node -p process.arch) > .build/packagelockhash
+        displayName: Prepare node_modules cache key
 
-- script: |
-    set -e
-    cat << EOF > ~/.netrc
-    machine github.com
-    login vscode
-    password $(github-distro-mixin-password)
-    EOF
+      - task: Cache@2
+        inputs:
+          key: '"node_modules" | .build/packagelockhash'
+          path: .build/node_modules_cache
+          cacheHitVar: NODE_MODULES_RESTORED
+        displayName: Restore node_modules cache
 
-    git config user.email "vscode@microsoft.com"
-    git config user.name "VSCode"
-  displayName: Prepare tooling
+      - script: tar -xzf .build/node_modules_cache/cache.tgz
+        condition: and(succeeded(), eq(variables.NODE_MODULES_RESTORED, 'true'))
+        displayName: Extract node_modules cache
 
-- script: |
-    set -e
-    git remote add distro "https://github.com/$(VSCODE_MIXIN_REPO).git"
-    git fetch distro
-    git merge $(node -p "require('./package.json').distro")
-  displayName: Merge distro
+      - script: |
+          set -e
+          # Set the private NPM registry to the global npmrc file
+          # so that authentication works for subfolders like build/, remote/, extensions/ etc
+          # which does not have their own .npmrc file
+          npm config set registry "$NPM_REGISTRY"
+          echo "##vso[task.setvariable variable=NPMRC_PATH]$(npm config get userconfig)"
+        condition: and(succeeded(), ne(variables['NPM_REGISTRY'], 'none'))
+        displayName: Setup NPM
 
-# - task: 1ESLighthouseEng.PipelineArtifactCaching.RestoreCacheV1.RestoreCache@1
-#   inputs:
-#     keyfile: 'build/.cachesalt, .yarnrc, remote/.yarnrc, **/yarn.lock, !**/node_modules/**/yarn.lock, !**/.*/**/yarn.lock'
-#     targetfolder: '**/node_modules, !**/node_modules/**/node_modules'
-#     vstsFeed: 'npm-vscode'
+      - task: npmAuthenticate@0
+        inputs:
+          workingFile: $(NPMRC_PATH)
+        condition: and(succeeded(), ne(variables['NPM_REGISTRY'], 'none'))
+        displayName: Setup NPM Authentication
 
-- script: |
-    set -e
-    CHILD_CONCURRENCY=1 yarn --frozen-lockfile
-  displayName: Install dependencies
-  # condition: and(succeeded(), ne(variables['CacheRestored'], 'true'))
+      - template: ../common/foundry-local.yml@self
+        parameters:
+          phase: prepare
 
-# - task: 1ESLighthouseEng.PipelineArtifactCaching.SaveCacheV1.SaveCache@1
-#   inputs:
-#     keyfile: 'build/.cachesalt, .yarnrc, remote/.yarnrc, **/yarn.lock, !**/node_modules/**/yarn.lock, !**/.*/**/yarn.lock'
-#     targetfolder: '**/node_modules, !**/node_modules/**/node_modules'
-#     vstsFeed: 'npm-vscode'
-#   condition: and(succeeded(), ne(variables['CacheRestored'], 'true'))
+      - script: |
+          set -e
+          ./build/azure-pipelines/linux/apt-retry.sh sudo apt-get update
+          ./build/azure-pipelines/linux/apt-retry.sh sudo apt-get install -y libkrb5-dev
+        displayName: Setup system services
+        condition: and(succeeded(), ne(variables.NODE_MODULES_RESTORED, 'true'))
 
-# - script: |
-#     set -e
-#     yarn postinstall
-#   displayName: Run postinstall scripts
-#   condition: and(succeeded(), eq(variables['CacheRestored'], 'true'))
+      - script: |
+          set -e
 
-- script: |
-    set -e
-    node build/azure-pipelines/mixin
-  displayName: Mix in quality
+          for i in {1..5}; do # try 5 times
+            npm ci && break
+            if [ $i -eq 5 ]; then
+              echo "Npm install failed too many times" >&2
+              exit 1
+            fi
+            echo "Npm install failed $i, trying again..."
+          done
+        env:
+          ELECTRON_SKIP_BINARY_DOWNLOAD: 1
+          PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1
+          GITHUB_TOKEN: "$(github-token-code-oss)"
+        displayName: Install dependencies
+        condition: and(succeeded(), ne(variables.NODE_MODULES_RESTORED, 'true'))
 
-- script: |
-    set -e
-    VSCODE_MIXIN_PASSWORD="$(github-distro-mixin-password)" \
-      yarn gulp vscode-web-min-ci
-  displayName: Build
+      - template: ../common/foundry-local.yml@self
+        parameters:
+          phase: install
 
-- script: |
-    set -e
-    AZURE_STORAGE_ACCOUNT="$(web-storage-account)" \
-    AZURE_STORAGE_ACCESS_KEY="$(web-storage-key)" \
-      node build/azure-pipelines/upload-cdn.js
-  displayName: Upload to CDN
+      - script: node build/azure-pipelines/common/checkNativeOptionalDeps.ts
+        displayName: Verify native optional dependency binaries
 
-  # upload only the workbench.web.api.js source maps because
-  # we just compiled these bits in the previous step and the
-  # general task to upload source maps has already been run
-- script: |
-    set -e
-    AZURE_STORAGE_ACCESS_KEY="$(ticino-storage-key)" \
-      node build/azure-pipelines/upload-sourcemaps out-vscode-web-min out-vscode-web-min/vs/workbench/workbench.web.api.js.map
-  displayName: Upload sourcemaps (Web)
+      - script: node build/azure-pipelines/distro/mixin-npm.ts
+        condition: and(succeeded(), ne(variables.NODE_MODULES_RESTORED, 'true'))
+        displayName: Mixin distro node modules
 
-- script: |
-    set -e
-    AZURE_DOCUMENTDB_MASTERKEY="$(builds-docdb-key-readwrite)" \
-    AZURE_STORAGE_ACCESS_KEY_2="$(vscode-storage-key)" \
-    VSCODE_MIXIN_PASSWORD="$(github-distro-mixin-password)" \
-    ./build/azure-pipelines/web/publish.sh
-  displayName: Publish
+      - script: |
+          set -e
+          node build/azure-pipelines/common/listNodeModules.ts .build/node_modules_list.txt
+          mkdir -p .build/node_modules_cache
+          tar -czf .build/node_modules_cache/cache.tgz --files-from .build/node_modules_list.txt
+        condition: and(succeeded(), ne(variables.NODE_MODULES_RESTORED, 'true'))
+        displayName: Create node_modules archive
+
+      - script: node build/azure-pipelines/distro/mixin-quality.ts
+        displayName: Mixin distro quality
+
+      - template: ../common/install-builtin-extensions.yml@self
+
+      - script: node build/npm/electronTypes.ts
+        displayName: Prepare Electron types
+
+      - script: npx deemon --detach --wait -- node build/azure-pipelines/common/downloadCopilotVsix.ts
+        env:
+          SYSTEM_ACCESSTOKEN: $(System.AccessToken)
+        displayName: Download Copilot VSIX (background)
+
+      - template: ../common/mixin-vscode-capi.yml@self
+
+      - script: npm run gulp core-ci
+        env:
+          GITHUB_TOKEN: "$(github-token-code-oss)"
+        displayName: Compile
+
+      - script: npx deemon --attach -- node build/azure-pipelines/common/downloadCopilotVsix.ts
+        env:
+          SYSTEM_ACCESSTOKEN: $(System.AccessToken)
+        displayName: Download Copilot VSIX
+
+      - script: |
+          set -e
+          npm run gulp vscode-web-min-ci
+          ARCHIVE_PATH="$(Build.ArtifactStagingDirectory)/out/web/vscode-web.tar.gz"
+          mkdir -p $(dirname $ARCHIVE_PATH)
+          tar --owner=0 --group=0 -czf $ARCHIVE_PATH -C .. vscode-web
+          echo "##vso[task.setvariable variable=WEB_PATH]$ARCHIVE_PATH"
+        env:
+          GITHUB_TOKEN: "$(github-token-code-oss)"
+        displayName: Build
+
+      - task: AzureCLI@2
+        displayName: Fetch secrets from Azure
+        inputs:
+          azureSubscription: vscode
+          scriptType: pscore
+          scriptLocation: inlineScript
+          addSpnToEnvironment: true
+          inlineScript: |
+            Write-Host "##vso[task.setvariable variable=AZURE_TENANT_ID]$env:tenantId"
+            Write-Host "##vso[task.setvariable variable=AZURE_CLIENT_ID]$env:servicePrincipalId"
+            Write-Host "##vso[task.setvariable variable=AZURE_ID_TOKEN;issecret=true]$env:idToken"
+
+      - script: |
+          set -e
+          AZURE_STORAGE_ACCOUNT="vscodeweb" \
+          AZURE_TENANT_ID="$(AZURE_TENANT_ID)" \
+          AZURE_CLIENT_ID="$(AZURE_CLIENT_ID)" \
+          AZURE_ID_TOKEN="$(AZURE_ID_TOKEN)" \
+            node build/azure-pipelines/upload-cdn.ts
+        displayName: Upload to CDN
+
+      - script: |
+          set -e
+          AZURE_STORAGE_ACCOUNT="vscodeweb" \
+          AZURE_TENANT_ID="$(AZURE_TENANT_ID)" \
+          AZURE_CLIENT_ID="$(AZURE_CLIENT_ID)" \
+          AZURE_ID_TOKEN="$(AZURE_ID_TOKEN)" \
+            node build/azure-pipelines/upload-sourcemaps.ts out-vscode-web-min out-vscode-web-min/vs/workbench/workbench.web.main.internal.js.map
+        displayName: Upload sourcemaps (Web)
+
+      - script: |
+          set -e
+          AZURE_STORAGE_ACCOUNT="vscodeweb" \
+          AZURE_TENANT_ID="$(AZURE_TENANT_ID)" \
+          AZURE_CLIENT_ID="$(AZURE_CLIENT_ID)" \
+          AZURE_ID_TOKEN="$(AZURE_ID_TOKEN)" \
+            node build/azure-pipelines/upload-nlsmetadata.ts
+        displayName: Upload NLS Metadata
